version: '3'
services:
  node:
    image: 'node:lts-alpine'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - '3333'
    command: 'npm run dev'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
